// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DwDefectDashboard: typeof import('./src/components/dwDefectDashboard/src/DwDefectDashboard.vue')['default']
    DwDefectFactorLine: typeof import('./src/components/dwDefectFactorLine/src/DwDefectFactorLine.vue')['default']
    DwDefectFactorPositionTraceLine: typeof import('./src/components/dwDefectFactorPositionTraceLine/src/DwDefectFactorPositionTraceLine.vue')['default']
    DwDefectPositionLine: typeof import('./src/components/dwDefectPositionLine/src/DwDefectPositionLine.vue')['default']
    DwDragVerify: typeof import('./src/components/dwDragVerify/src/DwDragVerify.vue')['default']
    DwEcharts: typeof import('./src/components/dwEcharts/src/DwEcharts.vue')['default']
    DwFilterArea: typeof import('./src/components/dwFilterArea/src/DwFilterArea.vue')['default']
    DwFilterAreaSlider: typeof import('./src/components/dwFilterAreaSlider/src/DwFilterAreaSlider.vue')['default']
    DwFilterRuler: typeof import('./src/components/dwFilterRuler/DwFilterRuler.vue')['default']
    DwFilterRulerSlider: typeof import('./src/components/dwFilterRulerSlider/src/DwFilterRulerSlider.vue')['default']
    DwFilterSlider: typeof import('./src/components/dwFilterSlider/src/DwFilterSlider.vue')['default']
    DwLineChart: typeof import('./src/components/dwLineChart/src/DwLineChart.vue')['default']
    DwPortfolioBg: typeof import('./src/components/dwPortfolioBg/src/DwPortfolioBg.vue')['default']
    DwPortfolioIcon: typeof import('./src/components/dwPortfolioIcon/src/DwPortfolioIcon.vue')['default']
    DwPortfolioIndustry: typeof import('./src/components/dwPortfolioIndustry/src/DwPortfolioIndustry.vue')['default']
    DwPortfolioLine: typeof import('./src/components/dwPortfolioLine/src/DwPortfolioLine.vue')['default']
    DwPortfolioNetWorth: typeof import('./src/components/dwPortfolioNetWorth/src/DwPortfolioNetWorth.vue')['default']
    DwPortfolioPie: typeof import('./src/components/dwPortfolioPie/src/DwPortfolioPie.vue')['default']
    DwStocksAnalysisLine: typeof import('./src/components/dwStocksAnalysisLine/src/DwStocksAnalysisLine.vue')['default']
    DwWechatLogin: typeof import('./src/components/dwWechatLogin/src/DwWechatLogin.vue')['default']
  }
}

export { }
